# Generated by Django 5.2 on 2025-07-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_login_email_login_first_name_login_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='last_name',
        ),
    ]
