# Generated by Django 5.2 on 2025-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_login_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
