# Generated by Django 5.2 on 2025-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_login_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='last_name',
        ),
        migrations.AddField(
            model_name='login',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
