# Generated by Django 5.2 on 2025-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_login_first_name_remove_login_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(choices=[('1', 'Member'), ('2', 'Encadrant')], default='1', max_length=1),
        ),
    ]
