# Generated by Django 5.2 on 2025-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_members'),
        ('users', '0007_login_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
