# Generated by Django 5.2 on 2025-07-31 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('nom_club', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
