# Generated by Django 5.2 on 2025-06-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('nom_club', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
